// examples/uni-vue3/src/components/stylex-card/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import * as stylex from 'weapp-stylex'
import { darkTheme, lightTheme, styles } from '../../styles'

const props = defineProps<{ dark: boolean }>()
const attrs = computed(() =>
  stylex.attrs(props.dark ? darkTheme : lightTheme, styles.card),
)
</script>

<template>
  <view id="stylex-card-root" :class="attrs.class" :style="attrs.style">
    组件样式也能复用
  </view>
</template>

// examples/taro-react/src/components/stylex-card/index.tsx
import { View } from '@tarojs/components'
import * as stylex from 'weapp-stylex'
import { darkTheme, lightTheme, styles } from '../../styles'

export default function StylexCard({ dark }: { dark: boolean }) {
  return (
    <View
      id="stylex-card-root"
      {...stylex.props(dark ? darkTheme : lightTheme, styles.card)}
    >
      组件样式也能复用
    </View>
  )
}
