// examples/taro-react/src/components/stylex-card/index.tsx
import { View } from '@tarojs/components'
import * as stylex from '@weapp-stylex/core'
import { darkTheme, lightTheme, styles } from '../../styles'

export default function StylexCard({ dark }: { dark: boolean }) {
  return (
    <View
      id="stylex-card-root"
      {...stylex.props(dark ? darkTheme : lightTheme, styles.card)}
    >
      组件样式也能复用
    </View>
  )
}

// examples/wechat-wevu/src/components/stylex-card/index.vue
<script setup lang="ts">
import * as stylex from '@weapp-stylex/core'
import { computed } from 'wevu'
import { darkTheme, lightTheme, styles } from '../../styles'

const props = defineProps<{ dark: boolean }>()
defineComponentJson({
  component: true,
  options: { styleIsolation: 'isolated' },
})
const attrs = computed(() =>
  stylex.attrs(props.dark ? darkTheme : lightTheme, styles.card),
)
</script>

<template>
  <view id="stylex-card-root" :class="attrs.class" :style="attrs.style">
    组件样式也能复用
  </view>
</template>
